### ISSUE TITLE
Is the bot dead?

### ISSUE THREAD

**Issue by LugiaDepression** [konstantinlevin77/discord-exchangebot#1]
I just added it but it's offline. I don't know if the bot is still active or abandoned

**Comment by konstantinlevin77** [comment]
> I just added it but it's offline. I don't know if the bot is still active or abandoned 

Hey, that's really awesome to see that you're interested in the bot. Unfortunately bot is abandoned but if you're still interested in the features you can clone the source code, get a discord bot token and a tenor token and host it on your own.

Have a good day :)
